import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import BaseLayout from "@/components/layouts/BaseLayout";
import { Button, Card, Col, Row } from "reactstrap";
import Link from "next/link";
import g1 from "../../public/images/g1.png";
import g2 from "../../public/images/g2.png";
import g3 from "../../public/images/g3.png";
import c1 from "../../public/images/checklist.png";
import c2 from "../../public/images/checklist2.png";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <Row>
          <Col lg={6} md={12} className="order-md-2 order-lg-1" style={{ paddingTop: "20vh" }}>
            <h2>Talenta terbaik negri untuk perubahan revolusi 4.0</h2>
            <p className="mt-2">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quisquam harum facere cumque, consequatur, inventore earum, consequuntur quis soluta nesciunt dolore similique minima vitae impedit excepturi. Esse minus aperiam cumque
              facere.
            </p>
            <Link href={"/search"}>
              <Button color="primary" size="lg" className="mt-3">
                Mulai Dari Sekarang
              </Button>
            </Link>
          </Col>
          <Col lg={6} md={12} className="order-md-1 order-lg-2">
            <Image src={g1} />
          </Col>
        </Row>
        <Row className="mt-5">
          <Col lg={6} md={12}>
            <Image src={g2} />
          </Col>
          <Col lg={6} md={12} style={{ marginTop: "15vh" }}>
            <h2>Kenapa harus mencari talent di peworld</h2>
            <p style={{ marginTop: "2vh" }}>
              <Image src={c1} /> Lorem ipsum dolor sit amet.
            </p>
            <p style={{ marginTop: "2vh" }}>
              <Image src={c1} /> Lorem ipsum dolor sit amet.
            </p>
            <p style={{ marginTop: "2vh" }}>
              <Image src={c1} /> Lorem ipsum dolor sit amet.
            </p>
            <p style={{ marginTop: "2vh" }}>
              <Image src={c1} /> Lorem ipsum dolor sit amet.
            </p>
          </Col>
        </Row>
        <Row className="mt-5">
          <Col lg={6} md={12} style={{ paddingTop: "10vh" }}>
            <h2>Skill Talent</h2>
            <p className="mt-4">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores commodi quod velit, provident consequuntur similique perferendis cumque, voluptatum, temporibus voluptate alias voluptatem quia minus quo maiores eos vel
              consectetur eveniet?
            </p>
            <Row>
              <Col lg={6} md={12}>
                <p style={{ marginTop: "2vh" }}>
                  <Image src={c2} /> Java
                </p>
                <p style={{ marginTop: "2vh" }}>
                  <Image src={c2} /> Kotlin
                </p>
                <p style={{ marginTop: "2vh" }}>
                  <Image src={c2} /> PHP
                </p>
                <p style={{ marginTop: "2vh" }}>
                  <Image src={c2} /> JavaScript
                </p>
              </Col>
              <Col lg={6} md={12}>
                <p style={{ marginTop: "2vh" }}>
                  <Image src={c2} /> Golang
                </p>
                <p style={{ marginTop: "2vh" }}>
                  <Image src={c2} /> C++
                </p>
                <p style={{ marginTop: "2vh" }}>
                  <Image src={c2} /> Ruby
                </p>
                <p style={{ marginTop: "2vh" }}>
                  <Image src={c2} /> 10+ Bahasa lainnya
                </p>
              </Col>
            </Row>
          </Col>
          <Col lg={6} md={12}>
            <Image src={g3} />
          </Col>
        </Row>
        <div className="justify-content-center mt-5">
          <Card style={{ borderRadius: "40px 8px 40px 8px", backgroundColor: "#5E50A1" }}>
            <div className="d-flex justify-content-around align-items-center mt-3 mb-3">
              <h2 style={{ color: "white" }}>Lorem ipsum dolor sit amet</h2>
              <Link href={"/search"}>
                <Button color="primary" size="lg" className="mt-3">
                  Mulai Dari Sekarang
                </Button>
              </Link>
            </div>
          </Card>
        </div>
      </BaseLayout>
    </>
  );
}
